from os import path

img_dir = path.join(path.dirname(__file__), 'img')

SC_WIDTH = 1920
SC_HIGHT = 1080
FPS = 60
P_INFO = 320
P_UP = 30
P_BOTTOM = 90

TILE = 64 
WIN_SIZE = (SC_WIDTH, SC_HIGHT)
VIEW_RECT = (0,P_UP,SC_WIDTH-P_INFO-1,SC_HIGHT-P_BOTTOM-1)
HALF_WIDTH = int((SC_WIDTH-P_INFO) / 2 / TILE)
HALF_HIGHT = int((SC_HIGHT-P_BOTTOM) / 2 / TILE)
FIELD_WIDTH = SC_WIDTH-P_INFO
FIELD_HIGHT = SC_HIGHT-P_BOTTOM-P_UP

INFO_WIDTH = P_INFO
INFO_HIGHT = SC_HIGHT
INFO_RECT = (FIELD_WIDTH, 0, SC_WIDTH-1, SC_HIGHT-1)

INV_WIDTH = SC_WIDTH-P_INFO
INV_HIGHT = P_BOTTOM
INV_RECT = (0,SC_HIGHT-P_BOTTOM,SC_WIDTH-P_INFO-1,SC_HIGHT)

PLANET_WIDTH = 100
PLANET_HIGHT = 100